base-url: "https://eselizabeth.github.io/inker-example"
webserver-port: "5005"
website-name: "inker website"
posts-per-page: "4"
pagination: "false"
icon-path: "favicon.png"
template-name: "navy"
generate-nav: "false"
extra:
  - { projects.md: "projects.html", visible-name: "projects" }
  - { about.md: "about.html", visible-name: "about" }
headers:
- "1. Introduction"
- "2. Configuration"
- "3. Templates and Extra content"
- "4. Deployment"