port: "5004"
website-name: "inker"
posts-per-page: "4"
pagination: "false"
icon-path: "favicon.png"
template-name: "bs-solar-doc"
generate-nav: "true"
headers:
- "1. Introduction"
- "2. Configuration"
- "3. Templates and Extra content"
- "4. Deployment"